# Generated by Django 3.1 on 2021-06-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosMarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
